version: "3.5"

services:
  dev:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - cache:/cache
      - build:/build
    depends_on:
      - db
    networks:
      - backend-net
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports

  agent:
    image: thishandp7/todobackend-ansible:latest
    volumes:
      - ../../ansible/prob.yml:/ansible/site.yml
    depends_on:
      - db
    networks:
      - backend-net
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"

  db:
    image: mysql:5.6
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend-net
    ports:
      - 3306

  builder:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../target:/wheelhouse
      - build:/build
    entrypoint: "entrypoint.sh"
    command: ["pip3", "wheel", "--no-index", "-f /build", "."]

networks:
  backend-net:
    driver: bridge

volumes:
  build:
    driver: local
  cache:
    external: true
