# Generated by Django 2.0.6 on 2018-06-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
