version: "3.5"

services:
  app:
    build:
      context: ../../
      dockerfile: docker/release/Dockerfile
    depends_on:
      - db
    networks:
      - backend-net
    volumes:
      - webroot:/var/www/todobackend
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.release
      MYSQL_HOST: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
    command:
      - uwsgi
      - "--socket /var/www/todobackend/todobackend.sock"
      - "--chmod-socket=666"
      - "--module todobackend.wsgi"
      - "--master"
      - "--die-on-term"

  nginx:
    image: nginx
    depends_on:
      - app
    volumes:
      - ./todobackend.conf:/etc/nginx/conf.d/todobackend.conf
      - webroot:/var/www/todobackend
    ports:
      - "8000:8000"
    networks:
      - frontend-net

  db:
    image: mysql:5.6
    ports:
      - "3306"
    networks:
      - backend-net
    environment:
      MYSQL_DATABASE: todobackend
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  agent:
    image: thishandp7/todobackend-ansible:latest
    volumes:
      - ../../ansible/prob.yml:/ansible/site.yml
    depends_on:
      - db
    networks:
      - backend-net
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"

  tests:
    image: thishandp7/todoapp_specs:latest
    depends_on:
      - nginx
    networks:
      - frontend-net
    environment:
      URL: http://nginx:8000/todos
      JUNIT_REPORT_PATH: /reports/acceptance.xml
      JUNIT_REPORT_STACK: 1
    command: --reporter mocha-jenkins-reporter

networks:
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge

volumes:
  webroot:
    driver: local
